import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { LogOutBtn } from "./LogoutBtn";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";
Link;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session = await getServerSession(authOptions);
  let res = cookies().get("name");
  console.log(res);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">write</Link>
          {session ? (
            <span>
              {session.user?.name}
              <LogOutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}
          <DarkMode />
        </div>{" "}
        {children}
      </body>
    </html>
  );
}
